name: Common Test

on:
  workflow_dispatch:
  push:

jobs:
  build_and_test:
    name: Build and test on Erlang/OTP ${{matrix.otp}} and rebar3 ${{matrix.rebar3}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['24.2']
        rebar3: ['3.19']
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install OTP and rebar3
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}

      - name: Install build dependencied
        run: |
          sudo apt-get update
          sudo apt-get -y install libssl-dev
          sudo apt-get -y install libsodium-dev
          sudo apt-get -y install libsnappy-dev

      - name: Start epmd
        run: epmd -daemon

      - name: Build and test bondy
        run: make test

