name: CI
on:
  push:
    branches : [develop, master]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+\+[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build an publish docker images to multiple registries
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            leapsight/bondy
            ghcr.io/leapsight/bondy
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
          flavor: |
            latest=false
            prefix=
            suffix=
          labels: |
            maintainer=Leapsight
            org.opencontainers.image.title=Bondy
            org.opencontainers.image.description=Bondy is an open source, always-on and scalable application networking platform for modern distributed architectures. It is an all-in-one event and service mesh with support for multiple communication patterns, multiple protocols and secure multi-tenancy.
            org.opencontainers.image.vendor=Leapsight
      -
        name: Build and push standard image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deployment/Dockerfile
          platforms: linux/amd64,linux/arm64
          # push: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Build and push alpine image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deployment/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64
          # push: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}-alpine
          labels: ${{ steps.meta.outputs.labels }}
      -
        # Copy multiplatform image from dockerhub to multiple registries
        # without changing the image SHA
        name: Copy Image to multiple registries
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: ${{ steps.meta.outputs.tags }}
          dst: |
            ghcr.io/${{ steps.meta.outputs.tags }}
      -
        # Copy multiplatform image from dockerhub to multiple registries
        # without changing the image SHA
        name: Copy Image to multiple registries
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: ${{ steps.meta.outputs.tags }}-alpine
          dst: |
            ghcr.io/${{ steps.meta.outputs.tags }}-alpine
